services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listeasy-landing
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
